import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path_provider/path_provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'app_providers.dart';
import 'data/repositories/bible_repository.dart';
import 'data/services/module_installer.dart';
import 'ui/app.dart';
import 'ui/features/library/view_models/library_view_preferences.dart';
import 'ui/features/reader/view_models/reader_preferences.dart';

/// The catalog index bundled with the application.
///
/// **This is metadata, not content.** It names eighteen resources, their licences, their
/// hashes and where their bytes live — no scripture, not a word of it. The engine
/// repository still contains no scripture text, which is the property D4 exists to protect,
/// and the `.amod` payloads are still fetched and verified at install time exactly as they
/// were before.
///
/// Bundling the *index* is a separate question from bundling the *content*, and the answer
/// differs for a reason that is worth stating rather than assuming: a bundle cannot be
/// refreshed without a release, so a catalog bundled this way goes stale. That is the real
/// cost, and it is paid knowingly. What it buys is that the application is not inert on
/// first run — which is the defect this section exists to fix. A library that lists nothing
/// and installs nothing is indistinguishable from a broken one.
///
/// The file is generated by `tool/sync_catalog.dart` from the catalog repository, and
/// `test/catalog_sync_test.dart` fails if the committed copy drifts from it. So the staleness
/// is bounded by a test rather than by good intentions.
const _catalogAsset = 'assets/catalog/catalog.json';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Resolved here, at the one place that is allowed to touch the platform channel, and
  // handed to the graph as a plain value. Views and ViewModels never learn where content
  // lives, which is what lets the tests swap in a temporary directory.
  final dir = await _resolveModuleDirectory();
  configureModulesDirectory(dir);

  // The catalog is a bundled asset, so it is read as a string rather than resolved through
  // a path. A null read is survivable: the library then lists installed modules and offers
  // nothing to install, which is the same behaviour as a user who has deleted the file.
  configureCatalog(await _readCatalog());

  // Preferences are opened before the first frame so the reader's settings and the
  // library's view mode are both applied on the first build rather than a frame later.
  final preferences = await SharedPreferences.getInstance();
  final overrides = <Override>[
    readerPreferencesStoreProvider.overrideWithValue(
      SharedPreferencesReaderStore(preferences),
    ),
    libraryViewPreferencesStoreProvider.overrideWithValue(
      SharedPreferencesLibraryViewStore(preferences),
    ),
  ];

  // Learned before the first frame so that a reference typed as the very first thing the
  // user does resolves. See [configureBookAliases] for why this cannot be lazy.
  configureBookAliases(await BibleRepository(ModuleStore(dir)).bookAliases());

  runApp(ProviderScope(overrides: overrides, child: const LogosApp()));
}

/// The catalog index, or null when the asset cannot be read.
Future<String?> _readCatalog() async {
  try {
    return await rootBundle.loadString(_catalogAsset);
  } on Object catch (e) {
    // Deliberately not fatal. The catalog is a description of what could be installed, and
    // the content already on disk is independent of it; refusing to start because a
    // manifest is missing would turn a degraded library into no library at all.
    debugPrint('bundled catalog could not be read, continuing without it: $e');
    return null;
  }
}

Future<Directory> _resolveModuleDirectory() async {
  final support = await getApplicationSupportDirectory();
  return Directory('${support.path}/modules');
}
